ARG NODE_VERSION
FROM node:$NODE_VERSION

# Add Yarn to the sources list
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
  && echo 'deb http://dl.yarnpkg.com/debian/ stable main' > /etc/apt/sources.list.d/yarn.list

RUN  apt-get update -qq && DEBIAN_FRONTEND=noninteractive apt-get install -yq --no-install-recommends  yarn
